title: Serendeepia Playbook
theme: jekyll-theme-minimal
collections:
  docs:
    output: true
    permalink: /:name
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.idea'
  - '_docs_internal'
  - '.gitignore'
  - 'CODEOWNERS'